search_url: 
categories_url: https://www.hiperlibertad.com.ar/api/catalog_system/pub/category/tree/3
proxy: True
proxy_ip_port: 37.19.220.180:8443
thread_number: 30
max_attempts: 2
delay_attempts: 3
pagination: 10
output_dir: C:\Users\LNKIZ\Desktop\testScrapingHLibertad\Scraper_Hlibertad_requests\salida